### PR TITLE
Allow BuildWrapper to stop a build

### PR DESCRIPTION
**Pull request by jorgenpt**
Adding this allows you to stop a build from a buildwrapper, like you can in java. (By returning false from the setup method)

### CODE REVIEW

**Comment by rtyler** [comment]
Went through this with @jorgenpt at his desk, it will break the prototype `logging_wrapper.rb` example, but I think this is the correct behavior needed to make BuildWrappers sane

**Comment by cowboyd** [comment]
What's wrong with failing explicitly?

I think that:

```
fail AbortException, "this thing totally happened, that like, totally screwed up my like, chances of completing this build"
```

reads much better than:

```
return false
```

Believe it or not, this was a deliberate decision to ignore the result of setup() and teardown()

We discussed this with @kohsuke and @nahi, and the consensus (I think) was that the boolean returning to determine whether a build should continue was an ugly convention, but necessary in the Java API to maintain backwards compatibility

**Comment by rtyler** [comment]
In that case shoukdn't teardown have the same behavior?

**Comment by cowboyd** [comment]
yep, I think the answer is to actually extend Jenkins::Tasks::Build to have the abort() method which underlyingly throws an AbortException

**Comment by jorgenpt** [comment]
So like I mentioned on IRC, this change or something similar (maybe using a custom exception) is needed, as AbortException forcefully changes the build result to FAILURE. Using my patch, you can set the build result to NOT_BUILT before returning, and have it be respected.

**Comment by jorgenpt** [comment]
(though I don't have the permission to reopen this pull req ;-)

**Comment by jorgenpt** [comment]
This should be more like what we talked about on IRC :-)

**Pull request merged**
